### PR TITLE
build(opm): add main_module specification 

### PR DESCRIPTION
**Pull request by mashirozx**
As docs said: https://opm.openresty.org/docs#main_module

With main_module specification, OPM modules can be required directly, no need to configure the Lua path.

### CODE REVIEW

**Comment by knyar** [comment]
Thank you!

**Comment by mashirozx** [comment]
When will be the time for the next release on OPM? 😁

**Comment by knyar** [comment]
> When will be the time for the next release on OPM? 😁

Already there: https://opm.openresty.org/package/knyar/nginx-lua-prometheus/

**Comment by mashirozx** [comment]
Thank you very much 💖

**Pull request merged**
