### PR TITLE
chore: use ngx.re.match instead of string match to improve performance

### LINKED ISSUE #130: optimize the long-tail request phenomenon
Hi, thank you for this great library. We have created prometheus plugin in Apache APISIX based on this library.

We found that long tail requests are generated in use and after verification, we found that this phenomenon is related to the `metric_data` function of this library. Original analysis reference: https://github.com/apache/apisix/issues/5755

Here are some tests I did

- applying pressure to `metric_data`: `wrk -t2 -c100 -d360s -R1000 --u_latency http://127.0.0.1:9080/hello`
- applying pressure to APISIX :`wrk -t2 -c100 -d360s -R1000 --u_latency http://127.0.0.1:9080/hello`

1. do nothing

      flamegraph:
      original_prometheus

    the result for wrk2 is
    ```
      Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
       50.000%    1.13ms
       75.000%    2.56ms
       90.000%    4.82ms
       99.000%   14.70ms
       99.900%   27.95ms
       99.990%   74.75ms
       99.999%  102.78ms
      100.000%  102.78ms
    ```
  
    the `fix_histogram_bucket_labels` function takes up too much CPU time

2. comments `fix_histogram_bucket_labels`

      flamegraph:
      rm_fix_histogram_bucket_labels

    the result for wrk2 is
    ```
        Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
       50.000%  420.00us
       75.000%  782.00us
       90.000%    1.80ms
       99.000%    8.57ms
       99.900%   27.61ms
       99.990%   57.34ms
       99.999%   85.57ms
      100.000%   95.68ms
    ```

     there are some changes, but not as much as I would like.

3.  comments `fix_histogram_bucket_labels` and add `ngx.sleep(0)`

     I add `ngx.sleep(0)` at the begin of loop in `metric_data` (here: https://github.com/knyar/nginx-lua-prometheus/blob/master/prometheus.lua#L821) to introduces periodic yielding points, also added `ngx.sleep(0)` to some places in the prometheus plugin for APISIX.

      flamegraph:
flame

    the result for wrk2 is
    ```
      Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
     50.000%  458.00us
     75.000%    0.93ms
     90.000%    3.25ms
     99.000%   20.53ms
     99.900%   38.05ms
     99.990%   51.97ms
     99.999%   59.39ms
    100.000%   66.24ms
    ```

    it now appears that the maximum request latency has been effectively improved.

---------------------------------------

I would like to discuss optimizing the `fix_histogram_bucket_labels` function and introducing periodic yielding points, after the results of the discussion, I would like to submit a PR for optimization.

### PR DESCRIPTION
**Pull request by tzssangglass**
fix: #130

### CODE REVIEW

**Comment by tzssangglass** [comment]
## before optimization

### flamegraph

flame-origin

### test results

```
  Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
 50.000%   11.18ms
 75.000%   17.41ms
 90.000%   23.66ms
 99.000%   45.57ms
 99.900%   92.22ms
 99.990%  123.71ms
 99.999%  136.83ms
100.000%  144.13ms
```

## after optimization

### flamegraph 

flame-optimize

### test results

```
  Latency Distribution (HdrHistogram - Uncorrected Latency (measured without taking delayed starts into account))
 50.000%    4.19ms
 75.000%    7.70ms
 90.000%   13.31ms
 99.000%   29.66ms
 99.900%   59.23ms
 99.990%   88.06ms
 99.999%  129.47ms
100.000%  129.79ms
```

Performance has improved, and the reason for this noticeable delay in requests is that I'm putting a lot of pressure on metrics_collect.

The direction of optimization can be continued

1. use more efficient regex
2. refactor this part of the code, preferably to eliminate the regular.

I'm trying.

**Comment by tzssangglass** [comment]
I'm learning how to add  integration test.

**Comment by tzssangglass** [comment]
I checked some of the `string` related functions 

- `string.gsub`: https://github.com/knyar/nginx-lua-prometheus/blob/f0b277ac92129b19d20cda587a8aab911fdca642/prometheus.lua#L170-L176 cannot be replaced by `ngx.re.gsub`, ref: https://github.com/openresty/lua-nginx-module#special-escaping-sequences. the other two have been replaced.
- `string.find`:  only plain string searches (no patterns) can be JIT-compiled by LuaJIT. The code is all strings and does not need to be optimised. ref: http://wiki.luajit.org/NYI
- `string.format`: now it's ok.
- `string.sub`:  cannot be optimised, it is supposed to generate new strings.

Although I have added test cases, I hardly know go, so I can't write complex test cases with go ......

**Comment by knyar** [comment]
This is great, thank you. Please let me know if you are done with this, and I'll be happy to get it merged.

**Comment by tzssangglass** [comment]
> This is great, thank you. Please let me know if you are done with this, and I'll be happy to get it merged.

Yes, it has been done.
 introduces periodic yielding points by `ngx.sleep(0)` will be submitted in the next PR.

**Pull request merged**
