### PR TITLE
Amend README.md

### PR DESCRIPTION
**Pull request by oldgreen**
Provide a list of allowed values of `host` label in lua code suggested by README.md to prevent Prometheus storage depletion by malicious HTTP clients.

### CODE REVIEW

**Comment by knyar** [comment]
This seems too complex for a simple example.

"Quick start guide" section has a note about using HTTP host as a metric label. If you think it's unclear, could you please propose better wording? Or do you think it might be better to completely remove the `host` label from the example?

**Comment by oldgreen** [comment]
Heh, sorry for closing this, it was not intentional. Please have a look at https://github.com/oldgreen/nginx-lua-prometheus/commit/2d3fb199694813e922eb80051c663a6a97c4663f - this seems better to me than the previous variant. The content of `server_name` is under the control of the admin, the content of `host` is not. https://nginx.org/en/docs/http/ngx_http_core_module.html#var_server_name

**Comment by knyar** [comment]
Thanks, @oldgreen, that's a good idea.

Fixed in a3fe529683d795688a8b27cf44ed0f90d87f8bb2

**Comment by oldgreen** [comment]
You're welcome. Thanks for providing this software.

**Pull request closed without merging**
